# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://hbtran.github.io',
                'git_url': 'https://github.com/hbtran/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.hello-world-core': { 'nbdev_hello_world.hello-world-core.HelloSayer': ( 'hello_world_core.html#hellosayer',
                                                                                                       'nbdev_hello_world/hello-world-core.py'),
                                                    'nbdev_hello_world.hello-world-core.HelloSayer.__init__': ( 'hello_world_core.html#hellosayer.__init__',
                                                                                                                'nbdev_hello_world/hello-world-core.py'),
                                                    'nbdev_hello_world.hello-world-core.HelloSayer.say': ( 'hello_world_core.html#hellosayer.say',
                                                                                                           'nbdev_hello_world/hello-world-core.py'),
                                                    'nbdev_hello_world.hello-world-core.foo': ( 'hello_world_core.html#foo',
                                                                                                'nbdev_hello_world/hello-world-core.py'),
                                                    'nbdev_hello_world.hello-world-core.say_hello': ( 'hello_world_core.html#say_hello',
                                                                                                      'nbdev_hello_world/hello-world-core.py')}}}
